# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kafka_grpc_io.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'kafka_grpc_io.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13kafka_grpc_io.proto\x12\rkafka_grpc_io\"\xa8\x01\n\x0eProduceRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\x0c\x12\r\n\x05value\x18\x03 \x01(\x0c\x12;\n\x07headers\x18\x04 \x03(\x0b\x32*.kafka_grpc_io.ProduceRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\\\n\x0fProduceResponse\x12\x0e\n\x06offset\x18\x01 \x01(\x03\x12\x11\n\tpartition\x18\x02 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\"I\n\x0e\x43onsumeRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x14\n\x0cnum_messages\x18\x02 \x01(\x03\x12\x12\n\ntimeout_ms\x18\x03 \x01(\x03\"\xbe\x01\n\x0f\x43onsumeResponse\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x0e\n\x06offset\x18\x03 \x01(\x03\x12\x11\n\tpartition\x18\x04 \x01(\x05\x12<\n\x07headers\x18\x05 \x03(\x0b\x32+.kafka_grpc_io.ConsumeResponse.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32\xa8\x01\n\x0cKafkaService\x12J\n\x07Produce\x12\x1d.kafka_grpc_io.ProduceRequest\x1a\x1e.kafka_grpc_io.ProduceResponse\"\x00\x12L\n\x07\x43onsume\x12\x1d.kafka_grpc_io.ConsumeRequest\x1a\x1e.kafka_grpc_io.ConsumeResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kafka_grpc_io_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCEREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_PRODUCEREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_CONSUMERESPONSE_HEADERSENTRY']._loaded_options = None
  _globals['_CONSUMERESPONSE_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_PRODUCEREQUEST']._serialized_start=39
  _globals['_PRODUCEREQUEST']._serialized_end=207
  _globals['_PRODUCEREQUEST_HEADERSENTRY']._serialized_start=161
  _globals['_PRODUCEREQUEST_HEADERSENTRY']._serialized_end=207
  _globals['_PRODUCERESPONSE']._serialized_start=209
  _globals['_PRODUCERESPONSE']._serialized_end=301
  _globals['_CONSUMEREQUEST']._serialized_start=303
  _globals['_CONSUMEREQUEST']._serialized_end=376
  _globals['_CONSUMERESPONSE']._serialized_start=379
  _globals['_CONSUMERESPONSE']._serialized_end=569
  _globals['_CONSUMERESPONSE_HEADERSENTRY']._serialized_start=161
  _globals['_CONSUMERESPONSE_HEADERSENTRY']._serialized_end=207
  _globals['_KAFKASERVICE']._serialized_start=572
  _globals['_KAFKASERVICE']._serialized_end=740
# @@protoc_insertion_point(module_scope)
